::: pyagenity.exceptions.graph_error
