::: pyagenity.exceptions.node_error
